-- DELETE PRECURSOR OF DATABASE
DROP DATABASE IF EXISTS employees_db;
-- CREATE DATABASE
CREATE DATABASE employees_db;
-- ENTER INTO DATABASE
USE employees_db;

-- TABLES: ID IS PRIMARY KEY
CREATE TABLE department(
  id INT NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
);

-- FOREIGN KEY HERE IS DEPARTMENT ID
CREATE TABLE employeeRole(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INT,
  FOREIGN KEY (department_id) REFERENCES department(id),
);

-- FOREIGN KEY HERE IS ROLE ID
CREATE TABLE employee(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT NOT NULL
  manager_id INT,
  FOREIGN KEY (role_id) REFERENCES role(id),
  FOREIGN KEY (manager_id) REFERENCES employee(id)
);